apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dbfbiyeep-nodejs 
  janus-idp.io/tekton: dbfbiyeep-nodejs
  backstage.io/kubernetes-id: dbfbiyeep-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dbfbiyeep-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml